name: flutter_classom
description: Classom view 

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  intl: ^0.16.1
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/main/
    - images/facility/
    - images/room/
    - images/room/drink/
    - images/room/korean/
    - images/room/western/
    - images/room/other/
    - images/claim/

  # example:
  fonts:
    - family: Gabriola
      fonts:
        - asset: fonts/Gabriola.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

